---
# MCP Servers Configuration
# 參考: .github/agents/context7.agent.md

mcp-servers:
  context7:
    type: http
    url: 'https://mcp.context7.com/mcp'
    headers: { 'CONTEXT7_API_KEY': '${{ secrets.COPILOT_MCP_CONTEXT7 }}' }
    tools: ['get-library-docs', 'resolve-library-id']

  # Supabase MCP server - 使用說明
  # 說明:
  # - 此段為示例，展示如何將 Supabase MCP endpoint 加入 `mcp-servers` 配置。
  # - 請避免在公開 repository 中明文放置授權金鑰。建議使用 GitHub Secrets 或 CI/CD 環境變數注入。
  #   例如在 GitHub Actions 中可用 `${{ secrets.SUPABASE_MCP_TOKEN }}` 來替代明文 token。
  # - `tools: ["*"]` 會允許該 MCP endpoint 使用所有可用的工具；只有在完全信任該 endpoint 時才授權。
  # 範例（安全作法）：使用 repository/CI secrets 注入專案識別與 token
  # 需要在 repository Secrets 中建立兩個值：
  # - SUPABASE_PROJECT_REF: Supabase project ref (例如 zecsbstjqjqoytwgjyct)
  # - SUPABASE_MCP_TOKEN: MCP 用的 Supabase token
  # 在 GitHub Actions 中可使用 ${{ secrets.SUPABASE_PROJECT_REF }} / ${{ secrets.SUPABASE_MCP_TOKEN }}
  supabase:
    type: http
    url: 'https://mcp.supabase.com/mcp?project_ref=${{ secrets.SUPABASE_PROJECT_REF }}'
    headers:
      Authorization: 'Bearer ${{ secrets.SUPABASE_MCP_TOKEN }}'
    tools: ['*']

  # 備註：
  # - 請勿在公開 repository 中放置明文 token。使用 Secrets 或 CI 環境變數注入。
  # - `tools: ['*']` 會授予該 endpoint 全部工具存取權限；僅在完全信任該 endpoint 時使用。

  # 本地工具（Local MCP servers）示例：透過 npx 啟動本機工具入口
  sequential-thinking:
    type: local
    command: npx
    args:
      - -y
      - '@modelcontextprotocol/server-sequential-thinking'
    tools: ['*']

  software-planning-tool:
    type: local
    command: npx
    args:
      - -y
      - 'github:NightTrek/Software-planning-mcp'
    tools: ['*']

  everything:
    type: local
    command: npx
    args:
      - -y
      - '@modelcontextprotocol/server-everything'
    tools: ['*']

  filesystem:
    type: local
    command: npx
    args:
      - -y
      - '@modelcontextprotocol/server-filesystem'
      - './'
    tools: ['*']

  time:
    type: local
    command: npx
    args:
      - -y
      - '@modelcontextprotocol/server-time'
    tools: ['*']

  fetch:
    type: local
    command: npx
    args:
      - -y
      - '@modelcontextprotocol/server-fetch'
    tools: ['*']
