# tasks.yaml
# ⚡ MCP Context7 Task Definitions
# Copilot Agent reads this file for passive, context-aware suggestions

tasks:
  - id: 1
    task: "Implement Login Feature"
    dependency: ["AuthService", "UI Components"]
    priority: "High"
    stakeholder: "Alice"
    status: "In Progress"
    notes: "Requires integration with OAuth2 provider"
    steps:
      - "STEP 1: Design login UI"
      - "STEP 2: Implement AuthService integration"
      - "STEP 3: Write unit tests"
      - "STEP 4: Validate OAuth2 flow"

  - id: 2
    task: "Create Dashboard Page"
    dependency: ["API Service", "Chart Library"]
    priority: "Medium"
    stakeholder: "Bob"
    status: "Pending"
    notes: "Include data visualization for user metrics"
    steps:
      - "STEP 1: Fetch data from API"
      - "STEP 2: Implement charts using Chart Library"
      - "STEP 3: Add responsive UI"
      - "STEP 4: Write integration tests"

  - id: 3
    task: "Refactor Notification System"
    dependency: ["MessagingService", "Database"]
    priority: "Low"
    stakeholder: "Charlie"
    status: "Pending"
    notes: "Improve performance and reliability"
    steps:
      - "STEP 1: Analyze current system"
      - "STEP 2: Optimize queries"
      - "STEP 3: Implement caching"
      - "STEP 4: Test with sample data"
