version: '1.0'

tasks:
  - id: 1
    task: 'Implement Login Feature'
    dependency: ['AuthService', 'UI Components']
    priority: 'High'
    status: 'In Progress'
    mcp_hints:
      - '使用 @context7 查詢 Firebase Auth 20.x 最新用法'
      - '用 @sequential-thinking 規劃登入流程'
    steps:
      - 'STEP 1: 查詢 Firebase Auth 文檔 (Context7)'
      - 'STEP 2: 設計登入流程 (Sequential-Thinking)'
      - 'STEP 3: 實作 AuthService'
      - 'STEP 4: 撰寫測試'

  - id: 2
    task: 'Query task events by Blueprint'
    dependency: ['EventStore', 'BlueprintService']
    priority: 'High'
    status: 'Active'
    mcp_hints:
      - '用 @context7 查詢 Firestore Query 最佳實踐'
      - '用 @sequential-thinking 分析 Event Causality 邏輯'
      - '用 @software-planning 追蹤子任務完成度'
    steps:
      - 'STEP 1: 驗證 Blueprint 權限'
      - 'STEP 2: 查詢 Firestore collection'
      - 'STEP 3: 追蹤 Event Causality'
