# Lint Agent Configuration
# Lint 代理配置

name: lint
description: "Specialized agent for code linting and formatting with MCP tools"

# MCP 工具用於 Lint
mcp_tools:
  primary:
    - filesystem  # 讀寫檔案
    - git  # 查看變更
    - github  # 檢查 CI status
  
  secondary:
    - sequential-thinking  # 分析問題
    - memory  # 記錄常見問題

# Lint 工具配置
lint_tools:
  eslint:
    config: "eslint.config.mjs"
    command: "yarn lint:ts"
    fix_command: "yarn lint:ts --fix"
    scope:
      - "**/*.ts"
      - "**/*.js"
      - "**/*.mjs"
    
    common_rules:
      - "@typescript-eslint/no-explicit-any"
      - "@typescript-eslint/no-unused-vars"
      - "@angular-eslint/use-lifecycle-interface"
      - "@angular-eslint/component-selector"
    
    mcp_workflow:
      - tool: filesystem.read_text_file
        params:
          path: "eslint.config.mjs"
      
      - tool: git.diff
        description: "查看變更的檔案"
      
      - tool: filesystem.grep
        params:
          pattern: "// eslint-disable"
        description: "檢查 disable 註解"
  
  stylelint:
    config: "stylelint.config.mjs"
    command: "yarn lint:style"
    fix_command: "yarn lint:style --fix"
    scope:
      - "**/*.css"
      - "**/*.scss"
      - "**/*.less"
    
    common_rules:
      - "declaration-block-no-duplicate-properties"
      - "color-hex-length"
      - "selector-pseudo-element-colon-notation"
      - "no-duplicate-selectors"
    
    mcp_workflow:
      - tool: filesystem.read_text_file
        params:
          path: "stylelint.config.mjs"
      
      - tool: filesystem.grep
        params:
          pattern: "stylelint-disable"
  
  prettier:
    config: ".prettierrc"
    command: "yarn format"
    fix_command: "yarn format"
    scope:
      - "**/*.ts"
      - "**/*.js"
      - "**/*.json"
      - "**/*.html"
      - "**/*.css"
      - "**/*.scss"

# Lint 流程
lint_workflow:
  pre_commit:
    description: "提交前 lint"
    steps:
      - name: "檢查變更檔案"
        tool: git.status
      
      - name: "執行 lint"
        commands:
          - "yarn lint:ts"
          - "yarn lint:style"
      
      - name: "自動修復"
        commands:
          - "yarn lint:ts --fix"
          - "yarn lint:style --fix"
      
      - name: "檢查剩餘問題"
        tool: sequential-thinking.sequentialthinking
  
  ci_lint:
    description: "CI 環境 lint"
    mcp_workflow:
      - tool: github.list_workflow_runs
        params:
          workflow_id: "ci.yml"
      
      - tool: github.get_job_logs
        params:
          job_id: "{lint_job_id}"
      
      - tool: github.summarize_job_log_failures
        description: "總結 lint 失敗原因"
  
  manual_lint:
    description: "手動 lint 檢查"
    mcp_workflow:
      - tool: filesystem.directory_tree
        description: "查看專案結構"
      
      - tool: filesystem.search_files
        params:
          pattern: "**/*.ts"
      
      - tool: sequential-thinking.sequentialthinking
        description: "分析需要 lint 的檔案"

# 常見 Lint 錯誤
common_lint_errors:
  typescript:
    no_explicit_any:
      rule: "@typescript-eslint/no-explicit-any"
      description: "不要使用 any 型別"
      fix: "使用具體型別或 unknown"
      example:
        bad: "function process(data: any) {}"
        good: "function process(data: User) {}"
    
    no_unused_vars:
      rule: "@typescript-eslint/no-unused-vars"
      description: "移除未使用的變數"
      fix: "刪除未使用的變數或加上 _ 前綴"
      example:
        bad: "const unused = 123;"
        good: "const _unused = 123; // 或直接刪除"
    
    no_non_null_assertion:
      rule: "@typescript-eslint/no-non-null-assertion"
      description: "避免使用 ! 非空斷言"
      fix: "使用型別守衛或 ?. 可選鏈"
      example:
        bad: "user.name!"
        good: "user?.name ?? 'Unknown'"
  
  angular:
    use_lifecycle_interface:
      rule: "@angular-eslint/use-lifecycle-interface"
      description: "實作生命週期介面"
      fix: "implements OnInit"
      example:
        bad: "class Component { ngOnInit() {} }"
        good: "class Component implements OnInit { ngOnInit() {} }"
    
    component_selector:
      rule: "@angular-eslint/component-selector"
      description: "使用正確的選擇器前綴"
      fix: "selector: 'app-example'"
      example:
        bad: "selector: 'example'"
        good: "selector: 'app-example'"
  
  style:
    declaration_block_no_duplicate:
      rule: "declaration-block-no-duplicate-properties"
      description: "不要重複屬性"
      fix: "移除重複的 CSS 屬性"
      example:
        bad: |
          .class {
            color: red;
            color: blue;
          }
        good: |
          .class {
            color: blue;
          }
    
    color_hex_length:
      rule: "color-hex-length"
      description: "使用短色碼"
      fix: "#fff 而非 #ffffff"
      example:
        bad: "color: #ffffff;"
        good: "color: #fff;"

# Lint 修復策略
fix_strategies:
  auto_fix:
    applicable:
      - "Formatting issues"
      - "Import sorting"
      - "Semicolons"
      - "Quotes"
    
    command: "yarn lint --fix"
    
    mcp_workflow:
      - tool: git.status
      - tool: filesystem.edit_file
      - tool: git.diff
  
  manual_fix:
    applicable:
      - "Type errors"
      - "Logic errors"
      - "Complex refactoring"
    
    workflow:
      - "分析錯誤原因"
      - "查詢文檔"
      - "實作修復"
      - "驗證修復"
    
    mcp_workflow:
      - tool: filesystem.read_text_file
      - tool: sequential-thinking.sequentialthinking
      - tool: filesystem.edit_file

# Lint 規則客製化
rule_customization:
  disable_rules:
    when: "特殊情況需要"
    how:
      inline: "// eslint-disable-next-line rule-name"
      block: "/* eslint-disable rule-name */"
      file: "/* eslint-disable */"
    
    best_practices:
      - "加上註解說明原因"
      - "儘量縮小範圍"
      - "考慮修復而非 disable"
  
  add_custom_rules:
    config_file: "eslint.config.mjs"
    example: |
      export default {
        rules: {
          'custom-rule': 'error',
          '@typescript-eslint/no-explicit-any': 'error'
        }
      }

# CI/CD 整合
ci_integration:
  github_actions:
    workflow: ".github/workflows/ci.yml"
    job: "lint"
    
    mcp_workflow:
      - tool: github.list_workflow_runs
        params:
          workflow_id: "ci.yml"
          status: "completed"
      
      - tool: github.get_job_logs
        params:
          job_id: "{lint_job_id}"
      
      - tool: github.summarize_job_log_failures
  
  pre_commit_hooks:
    tool: "husky"
    hooks:
      - "pre-commit: yarn lint-staged"
      - "commit-msg: yarn commitlint"

# Lint 報告
lint_report:
  format: "JSON / HTML / Text"
  
  sections:
    summary:
      - "Total files"
      - "Total errors"
      - "Total warnings"
      - "Fixable issues"
    
    by_rule:
      - "Rule name"
      - "Occurrences"
      - "Severity"
    
    by_file:
      - "File path"
      - "Error count"
      - "Warning count"
  
  mcp_workflow:
    - tool: filesystem.write_file
      params:
        path: "lint-report.json"
    
    - tool: memory.create_entities
      description: "記錄常見問題"

# Lint 最佳實踐
best_practices:
  - "定期執行 lint"
  - "修復 lint 錯誤再提交"
  - "使用 auto-fix 功能"
  - "理解規則原因"
  - "避免過度 disable"
  - "團隊共識規則"
  - "保持配置更新"

# Lint 檢查清單
lint_checklist:
  - "[ ] ESLint 通過"
  - "[ ] Stylelint 通過"
  - "[ ] Prettier 格式化"
  - "[ ] 無 lint-disable"
  - "[ ] 無 TypeScript 錯誤"
  - "[ ] 無 Angular 警告"
