# Release Agent Configuration
# 發布代理配置

name: release
description: "Specialized agent for release management and versioning with MCP tools"

# MCP 工具用於發布
mcp_tools:
  primary:
    - github  # Release 管理
    - git  # 版本控制
    - filesystem  # 讀寫檔案
  
  secondary:
    - supabase  # 資料庫遷移
    - sequential-thinking  # 發布計畫分析
    - memory  # 記錄發布歷史

# GitHub Release 工具
github_release_tools:
  - list_releases  # 列出所有 releases
  - get_latest_release  # 取得最新 release
  - get_release_by_tag  # 透過 tag 取得 release
  
  workflow:
    - tool: github.list_releases
      params:
        per_page: 10
    
    - tool: github.get_latest_release
      description: "檢查目前版本"
    
    - tool: github.get_release_by_tag
      params:
        tag: "v{version}"

# 版本策略
versioning_strategy:
  semantic_versioning:
    format: "MAJOR.MINOR.PATCH"
    rules:
      major:
        - "Breaking changes"
        - "Major new features"
        - "Incompatible API changes"
      
      minor:
        - "New features (backward compatible)"
        - "New components"
        - "New APIs"
      
      patch:
        - "Bug fixes"
        - "Performance improvements"
        - "Documentation updates"
    
    examples:
      - "1.0.0 → 2.0.0 (Breaking change)"
      - "1.0.0 → 1.1.0 (New feature)"
      - "1.0.0 → 1.0.1 (Bug fix)"
  
  pre_release:
    formats:
      alpha: "1.0.0-alpha.1"
      beta: "1.0.0-beta.1"
      rc: "1.0.0-rc.1"
    
    usage:
      - "Alpha: Internal testing"
      - "Beta: Public testing"
      - "RC: Release candidate"

# 發布流程
release_workflow:
  steps:
    - name: "版本規劃"
      description: "決定版本號與變更內容"
      mcp_tools:
        - sequential-thinking.sequentialthinking
        - github.list_releases
      
      tasks:
        - "Review commits since last release"
        - "Identify breaking changes"
        - "Determine version number"
        - "Plan release notes"
    
    - name: "更新版本"
      description: "更新 package.json 與相關檔案"
      mcp_tools:
        - filesystem.read_text_file
        - filesystem.edit_file
      
      files:
        - "package.json"
        - "package-lock.json"
        - "CHANGELOG.md"
    
    - name: "建置與測試"
      description: "確保所有測試通過"
      mcp_tools:
        - github.list_workflow_runs
        - github.get_job_logs
      
      checks:
        - "Lint passes"
        - "Build succeeds"
        - "All tests pass"
        - "Coverage meets threshold"
    
    - name: "資料庫遷移"
      description: "應用資料庫變更"
      mcp_tools:
        - supabase.list_migrations
        - supabase.merge_branch
      
      tasks:
        - "Review migrations"
        - "Test on staging"
        - "Merge to production"
    
    - name: "建立 Git Tag"
      description: "標記發布版本"
      mcp_tools:
        - git.commit
        - git.push
      
      commands:
        - "git tag -a v{version} -m 'Release v{version}'"
        - "git push origin v{version}"
    
    - name: "建立 GitHub Release"
      description: "發布到 GitHub"
      mcp_tools:
        - github.get_release_by_tag
      
      content:
        - "Release notes"
        - "Changelog"
        - "Download links"
        - "Breaking changes"
    
    - name: "部署"
      description: "部署到 production"
      mcp_tools:
        - github.list_workflow_runs
      
      tasks:
        - "Trigger deployment workflow"
        - "Monitor deployment"
        - "Verify deployment"
    
    - name: "發布後檢查"
      description: "驗證發布成功"
      mcp_tools:
        - github.get_latest_release
        - supabase.get_advisors
      
      checks:
        - "Application running"
        - "No errors in logs"
        - "Database healthy"
        - "APIs responding"

# CHANGELOG 生成
changelog_generation:
  format: "Keep a Changelog"
  sections:
    added:
      heading: "### Added"
      commits_pattern: "^feat:"
    
    changed:
      heading: "### Changed"
      commits_pattern: "^refactor:|^perf:"
    
    deprecated:
      heading: "### Deprecated"
      commits_pattern: "^deprecate:"
    
    removed:
      heading: "### Removed"
      commits_pattern: "^remove:"
    
    fixed:
      heading: "### Fixed"
      commits_pattern: "^fix:"
    
    security:
      heading: "### Security"
      commits_pattern: "^security:"
  
  mcp_workflow:
    - tool: git.log
      description: "取得 commits"
    
    - tool: filesystem.read_text_file
      params:
        path: "CHANGELOG.md"
    
    - tool: filesystem.edit_file
      description: "更新 CHANGELOG"
  
  template: |
    # Changelog
    
    All notable changes to this project will be documented in this file.
    
    The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
    
    ## [Unreleased]
    
    ## [{version}] - {date}
    
    ### Added
    {added_items}
    
    ### Changed
    {changed_items}
    
    ### Fixed
    {fixed_items}
    
    ### Security
    {security_items}

# Release Notes 生成
release_notes_generation:
  mcp_workflow:
    - tool: git.log
      description: "取得變更"
    
    - tool: sequential-thinking.sequentialthinking
      description: "分析重要變更"
    
    - tool: github.get_release_by_tag
      description: "檢查前一版本"
    
    - tool: filesystem.write_file
      params:
        path: "release-notes.md"
  
  template: |
    # Release v{version}
    
    Released on {date}
    
    ## Highlights
    {highlights}
    
    ## What's New
    {new_features}
    
    ## Improvements
    {improvements}
    
    ## Bug Fixes
    {bug_fixes}
    
    ## Breaking Changes
    {breaking_changes}
    
    ## Migration Guide
    {migration_guide}
    
    ## Full Changelog
    See [CHANGELOG.md](./CHANGELOG.md)
    
    ## Download
    - [Source code (zip)](link)
    - [Source code (tar.gz)](link)

# Hotfix 流程
hotfix_workflow:
  trigger: "Critical bug in production"
  
  steps:
    - name: "建立 hotfix 分支"
      mcp_tools:
        - git.branch
      command: "git checkout -b hotfix/{version} main"
    
    - name: "修復 bug"
      description: "實作修復"
    
    - name: "測試"
      mcp_tools:
        - github.list_workflow_runs
      description: "確保修復有效"
    
    - name: "更新版本 (PATCH)"
      mcp_tools:
        - filesystem.edit_file
      files:
        - "package.json"
        - "CHANGELOG.md"
    
    - name: "合併到 main"
      mcp_tools:
        - git.commit
        - git.push
    
    - name: "建立 release"
      mcp_tools:
        - github.get_release_by_tag
    
    - name: "部署"
      description: "立即部署到 production"
    
    - name: "合併回 develop"
      description: "確保 develop 包含修復"

# 發布檢查清單
release_checklist:
  pre_release:
    - "[ ] All tests passing"
    - "[ ] Documentation updated"
    - "[ ] CHANGELOG updated"
    - "[ ] Version number bumped"
    - "[ ] Migration scripts tested"
    - "[ ] Breaking changes documented"
    - "[ ] Security audit completed"
  
  release:
    - "[ ] Git tag created"
    - "[ ] GitHub release created"
    - "[ ] Release notes published"
    - "[ ] Deployment successful"
    - "[ ] Monitoring active"
  
  post_release:
    - "[ ] Application healthy"
    - "[ ] No critical errors"
    - "[ ] Database migrated"
    - "[ ] Team notified"
    - "[ ] Social media updated"

# 回滾計畫
rollback_plan:
  trigger: "Critical issue after release"
  
  steps:
    - name: "評估問題"
      mcp_tools:
        - supabase.get_logs
        - github.get_job_logs
    
    - name: "決定回滾"
      description: "是否需要回滾"
    
    - name: "資料庫回滾"
      mcp_tools:
        - supabase.reset_branch
      description: "回滾到前一版本"
    
    - name: "應用程式回滾"
      mcp_tools:
        - github.list_releases
        - github.get_release_by_tag
      description: "部署前一版本"
    
    - name: "驗證回滾"
      description: "確認系統正常"
    
    - name: "通知團隊"
      description: "說明回滾原因"

# 發布最佳實踐
best_practices:
  - "遵循 Semantic Versioning"
  - "維護 CHANGELOG"
  - "自動化測試"
  - "Staging 環境驗證"
  - "資料庫遷移測試"
  - "準備回滾計畫"
  - "監控部署"
  - "記錄發布歷史"
  - "團隊溝通"
  - "使用者通知"
