/*
 * Automatically generated by 'ng g ng-alain:plugin icon'
 * @see https://ng-alain.com/cli/plugin#icon
 *
 * 圖標導入策略：
 * - 本檔案包含專案中實際使用的圖標
 * - 定期執行 `yarn icon` 可自動更新此檔案
 * - 僅導入需要的圖標以優化 bundle 大小
 *
 * 優化建議：
 * 1. 定期審查並移除未使用的圖標
 * 2. 使用 ng-alain icon 插件自動管理
 * 3. 考慮使用動態載入減少初始 bundle
 */

// All icons imported from a single source to avoid duplicate imports
import {
  // 導航相關圖標 (高頻使用)
  DashboardOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  AppstoreOutline,
  RocketOutline,
  ProjectOutline,
  GoldOutline,
  // 用戶與權限相關
  UserOutline,
  TeamOutline,
  LogoutOutline,
  LockOutline,
  UsergroupAddOutline,
  // 操作相關圖標
  SettingOutline,
  ToolOutline,
  DownloadOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  ScanOutline,
  PrinterOutline,
  ShareAltOutline,
  // 通訊與社交
  MailOutline,
  MessageOutline,
  GlobalOutline,
  GithubOutline,
  WeiboCircleOutline,
  AlipayCircleOutline,
  TaobaoCircleOutline,
  DingdingOutline,
  TaobaoOutline,
  // 數據與分析
  PieChartOutline,
  DatabaseOutline,
  HddOutline,
  CloudOutline,
  ApiOutline,
  ForkOutline,
  // 裝置與硬體
  LaptopOutline,
  UsbOutline,
  CustomerServiceOutline,
  SoundOutline,
  // 內容與文檔
  BookOutline,
  BorderLeftOutline,
  BorderRightOutline,
  // 商務與金融
  PayCircleOutline,
  ShoppingCartOutline,
  TrophyOutline,
  CopyrightOutline,
  // 互動與反饋
  LikeOutline,
  DislikeOutline,
  StarOutline,
  FrownOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  // 編輯與操作
  EditOutline,
  DeleteOutline,
  SaveOutline,
  CloseOutline,
  CheckCircleOutline,
  CheckSquareOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  EyeOutline,
  EyeInvisibleOutline,
  SwapOutline,
  ReloadOutline,
  ZoomInOutline,
  ZoomOutOutline,
  // 文件與內容
  FileTextOutline,
  PaperClipOutline,
  PictureOutline,
  UnorderedListOutline,
  // 時間與狀態
  ClockCircleOutline,
  HistoryOutline,
  PlayCircleOutline,
  PauseCircleOutline,
  // 通知與警告
  NotificationOutline,
  WarningOutline,
  ExclamationCircleOutline,
  // 建築與部署
  ApartmentOutline,
  ClusterOutline,
  ContainerOutline,
  DeploymentUnitOutline,
  // 圖表與數據視覺化
  BarChartOutline,
  LineChartOutline,
  RadarChartOutline,
  FundOutline,
  // 位置與導航
  HomeOutline,
  InboxOutline,
  FlagOutline,
  // 財務與交易
  DollarOutline,
  TransactionOutline,
  // 用戶管理擴展
  UserAddOutline,
  UserDeleteOutline,
  CrownOutline,
  // 特效與動作
  ThunderboltOutline
} from '@ant-design/icons-angular/icons';

/**
 * 自動生成的圖標列表
 * 包含專案中實際使用的所有圖標
 *
 * 維護建議：
 * - 新增圖標：執行 `yarn icon` 自動掃描並更新
 * - 移除未使用圖標：定期審查並手動移除
 * - 圖標命名：遵循 Ant Design 命名規範
 */
export const ICONS_AUTO = [
  // 導航相關 (Navigation)
  DashboardOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  AppstoreOutline,
  RocketOutline,
  ProjectOutline, // 新增
  GoldOutline,

  // 用戶與權限 (User & Auth)
  UserOutline,
  TeamOutline,
  LogoutOutline,
  LockOutline,
  UsergroupAddOutline, // 新增

  // 操作相關 (Actions)
  SettingOutline,
  ToolOutline,
  DownloadOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  ScanOutline,
  PrinterOutline,
  ShareAltOutline,

  // 通訊與社交 (Communication & Social)
  MailOutline,
  MessageOutline,
  GlobalOutline,
  GithubOutline,
  WeiboCircleOutline,
  AlipayCircleOutline,
  TaobaoCircleOutline,
  DingdingOutline,
  TaobaoOutline,

  // 數據與分析 (Data & Analytics)
  PieChartOutline,
  DatabaseOutline,
  HddOutline,
  CloudOutline,
  ApiOutline,
  ForkOutline,

  // 裝置與硬體 (Devices & Hardware)
  LaptopOutline,
  UsbOutline,
  CustomerServiceOutline,
  SoundOutline,

  // 內容與文檔 (Content & Documents)
  BookOutline,
  BorderLeftOutline,
  BorderRightOutline,

  // 商務與金融 (Business & Finance)
  PayCircleOutline,
  ShoppingCartOutline,
  TrophyOutline,
  CopyrightOutline,

  // 互動與反饋 (Interaction & Feedback)
  LikeOutline,
  DislikeOutline,
  StarOutline,
  FrownOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,

  // 編輯與操作 (Edit & Actions)
  EditOutline,
  DeleteOutline,
  SaveOutline,
  CloseOutline,
  CheckCircleOutline,
  CheckSquareOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  EyeOutline,
  EyeInvisibleOutline,
  SwapOutline,
  ReloadOutline,
  ZoomInOutline,
  ZoomOutOutline,

  // 文件與內容 (Files & Content)
  FileTextOutline,
  PaperClipOutline,
  PictureOutline,
  UnorderedListOutline,

  // 時間與狀態 (Time & Status)
  ClockCircleOutline,
  HistoryOutline,
  PlayCircleOutline,
  PauseCircleOutline,

  // 通知與警告 (Notifications & Warnings)
  NotificationOutline,
  WarningOutline,
  ExclamationCircleOutline,

  // 建築與部署 (Architecture & Deployment)
  ApartmentOutline,
  ClusterOutline,
  ContainerOutline,
  DeploymentUnitOutline,

  // 圖表與數據視覺化 (Charts & Data Visualization)
  BarChartOutline,
  LineChartOutline,
  RadarChartOutline,
  FundOutline,

  // 位置與導航 (Location & Navigation)
  HomeOutline,
  InboxOutline,
  FlagOutline,

  // 財務與交易 (Finance & Transactions)
  DollarOutline,
  TransactionOutline,

  // 用戶管理擴展 (User Management Extended)
  UserAddOutline,
  UserDeleteOutline,
  CrownOutline,

  // 特效與動作 (Effects & Actions)
  ThunderboltOutline
];
